name: Claude Sonnet 4 Agent

on:
  # Automatic review when PR is opened
  pull_request:
    types: [opened]
  # Manual reviews via @sonnet mentions
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@sonnet')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@sonnet')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@sonnet'))
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_API_KEY_2 }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"

          # Automatic review prompt for PR opened events
          direct_prompt: |
            ${{ github.event_name == 'pull_request' && '
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.

            ⚡ **Claude Sonnet 4** automated PR review
            ' || '' }}

          # Manual trigger phrase for comment-based reviews (when direct_prompt is empty)
          trigger_phrase: '@sonnet'

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"

          # Optional: Allow Claude to run specific commands
          # allowed_tools: "Bash(npm install),Bash(npm run build),Bash(npm run test:*),Bash(npm run lint:*)"

          # Optional: Add custom instructions for Claude to customize its behavior for your project
          custom_instructions: |
            ${{ github.event_name != 'pull_request' && '⚡ **Claude Sonnet 4** responding:' || '' }}

            Follow our coding standards
            Ensure all new code has tests
            Use TypeScript for new files

          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test
